; Zero Page Register File definition
R0 = $00
R1 = $01
R2 = $02
R3 = $03
R4 = $04
R5 = $05
R6 = $06
R7 = $07

; Alias high/low bytes for vbcc 16-bit register tracking
R0L = R0
R0H = R0+1
R1L = R1
R1H = R1+1
R2L = R2
R2H = R2+1
R3L = R3
R3H = R3+1
R4L = R4
R4H = R4+1
R5L = R5
R5H = R5+1
R6L = R6
R6H = R6+1
R7L = R7
R7H = R7+1

NULL = $00
CR   = $0D
LF   = $0A
BS   = $08
DEL  = $7F 
TAB  = $09
SPC  = $20

